enabled: true
database:
  host: '{{ .Release.Name }}-postgresql'
  username: ''
  password: ''
  dbName:
awsSecretName: 'quilt-backups'
endpoint: 'https://s3.eu-central-003.backblazeb2.com'
image: 'ghcr.io/quiltmc/postgresql-s3-backup:b837205'
